# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IWZZ4+qdq3zmsc1sFwUhVonn0kj5Sk9G8xKKPr/E5ZtsOG7abtcmiDQyNVbpgeb+Q7HoSzmOf0iEjACoqIQV7+15/nfyTfxsywZdPRE+LV/PtHLTXOSeLdTGzVRihkgsza4Od/pO6U6hhy7E99kv+ieVHOjzow9G5UuEj+hJicSu8ce3FmdHushy0M+dKlBpv4f0Dy+UGVGVuWIL3eNuUqjk4ui+OCBOZwzpdK6Qky1wZg8JjY5EZsMXzzAnMaRDXPVm/WnzuTXO7f0KASpA0QNhCg7LVEmPbbpg3iEyxbBen4n9S7O/6YPaZQgXYcVkh4lYE/CpXjlerepl0GqssP6nOGGSzIojMlyNRqo3k6QHoK1lSvm2SAjQb6dlwDTNWvzRPzVJk9yGc5BMpd1cJWfx8nX9ZF5ay++xLtFsmzcS+iRebDxeMK/qRlnByG7QmVzRnbLTtZbkxISVQZl8P+Y8fR007xjMmozAqbGDr/n+eyr8we/L5D/qVrulpTCBgfASKefiHRUC4enflC9xnXJ7ltBQSswXW91xId1IH87o+S79kfPfdd2Z5DQHSlTRwvOMqyEjphHndYtd/LJWyVhCTkbpDWMFfCWtQZTdhLE0Zz3M7GXitMziiAR8ofXGqeltIAcmHz+5VRmlOOiekxAIe0uRUtnOPgmfcyo1YwI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml