# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IWZZ4+qdq3zmsc1sFwUhVonn0kj5Sk9G8xKKPr/E5ZtsOG7abtcmiDQyNVbpgeb+Q7HoSzmOf0iEjACoqIQV7+15/nfyTfxsywZdPRE+LV/PtHLTXOSeLdTGzVRihkgsza4Od/pO6U6hhy7E99kv+ieVHOjzow9G5UuEj+hJicSu8ce3FmdHushy0M+dKlBpv4f0Dy+UGVGVuWIL3eNuUqjk4ui+OCBOZwzpdK6Qky1wZg8JjY5EZsMXzzAnMaRDXPVm/WnzuTXO7f0KASpA0QNhCg7LVEmPbbpg3iEyxbBen4n9S7O/6YPaZQgXYcVkh4lYE/CpXjlerepl0GqssP6nOGGSzIojMlyNRqo3k6QHoK1lSvm2SAjQb6dlwDTNWvzRPzVJk9yGc5BMpd1cJWfx8nX9ZF5ay++xLtFsmzcS+iRebDxeMK/qRlnByG7QmVzRnbLTtZbkxISVQZl8P+Y8fR007xjMmozAqbGDr/n+eyr8we/L5D/qVrulpTCBgfASKefiHRUC4enflC9xnXJ7ltBQSswXW91xId1IH87o+S79kfPfdd2Z5DQHSlTRwvOMqyEjphHndYtd/LJWyVhCTkbpDWMFfCWtQZTdhLE0Zz3M7GXitMziiAR8ofXGqeltIAcmHz+5VRmlOOiekxAIe0uRUtnOPgmfcyo1YwI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
