travis:
  secure:
    BINSTAR_TOKEN: q24TNpKt5wlf3OpselGAB/ySL6pWSrUZnKA7paxHU9jpiH5hTWCOqiY/eBAAdPrCMFMGgg043vs6nQekT/yiHXzDpmEZWoIinukfOcgpf5mfy/tXP4odwhhLSbLm7OXKQFeSa+4noFZWPiaSuZIWgHw5mT4yi0z/Na5AFBye2I4K2RFA2eiQofPeUNxi1Mm28WQPf3/WUbVSTf4biyEoFRX9K53dJUtQL75HOvwoCOqy7wjc7Z/LIdHqckJvMgNT/DcKmyQtXW+UmlhPQEiKQEModC5fPek91wJr7fQvYu1Dy5O7X1pCXm8cDRuGQ5n0Xu+BkM3NOaaBuBtViDL5S98SyKc0Y2BKHie/q1rpbjQL5SxrNpOiYHaluUivimWSs9U2qNgZLaG0ktFRQvDetL2eS2KRzOgcjQYNKskXR6W0quTLOOWBTXj/Zrp2hIzwi9fX+M/HeFn0kta4t4sG2uZX9/3YJC7rZKGCJ+BclhXglE0iOn9jHwucxDBISLo5xREEyZ8j8rzF9ADdREVJL3ojadC15ChxZ8NMsLHfVAbuP440iJOfoAj84Z3z3eQAPqcE+VdsuM4y/kBS6VlPlQ6SQw7p+rrlA13d/j6UO4Ng/RiWbTw2tSCtD4+ukoe0EXqmY0A0KRHAwhI3PDeF1+iTsBsYa4zVWHRTpLcWNoA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
